# -*- coding: utf-8 -*-
"""Chennai_Temperature_Forecasting_Using_ARIMA_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXuGRVpBGDqTrEZTF9yPSyGerm5n3QgD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA

from sklearn.metrics import mean_squared_error
from math import sqrt

import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('Indian_Climate_Dataset_2024_2025.csv')

df.head()

"""Filter Chennai Data"""

chennai = df[df['City'] == 'Chennai'].copy()

print(chennai.shape)

chennai.head()

"""Convert Date Column"""

chennai['Date'] = pd.to_datetime(chennai['Date'])

chennai.set_index('Date', inplace=True)

chennai.head()

"""Select Target Variable

Using Average Temperature
"""

print(chennai.columns)

data = chennai['Temperature_Avg (°C)']

data.head()

"""Check Missing Values"""

print(data.isnull().sum())

data = data.dropna()

"""Plot Temperature Series"""

plt.figure(figsize=(14,5))

plt.plot(data)

plt.title("Chennai Average Temperature")

plt.xlabel("Date")

plt.ylabel("Temperature")

plt.grid(True)

plt.show()

"""ADF Test"""

result = adfuller(data)

print("ADF Statistic :", result[0])
print("P-value :", result[1])

for key, value in result[4].items():
    print(key, value)

"""Convert to Decimal Format"""

import numpy as np

p_value = 2.1136041501846105e-30

print(np.format_float_positional(p_value))

"""P-Value < 0.05
Chennai temperature series is stationary.
"""

if result[1] < 0.05:
    print("Stationary Data")
else:
    print("Non-Stationary Data")

"""Differencing"""

data_diff = data.diff().dropna()

"""Plot Differenced Data"""

plt.figure(figsize=(14,5))

plt.plot(data_diff)

plt.title("Differenced Temperature Series")

plt.grid(True)

plt.show()

"""ADF Test After Differencing"""

result = adfuller(data_diff)

print("ADF Statistic :", result[0])
print("P-value :", result[1])

import numpy as np

p_value = 4.374853215094208e-21

print(np.format_float_positional(p_value))

"""| Parameter | Value |
| --------- | ----- |
| d         | 0     |
=====
Before Differencing

2.11 × 10⁻³⁰ < 0.05

✅ Stationary
======

After Differencing
P-value
4.37 × 10⁻²¹

Again:

4.37 × 10⁻²¹ < 0.05

✅ Stationary
======

did not need differencing because the original Chennai temperature series was already stationary.

ACF Plot (Find q)
"""

from statsmodels.graphics.tsaplots import plot_acf
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plot_acf(data, lags=30)
plt.show()

"""PACF Plot (Find p)"""

from statsmodels.graphics.tsaplots import plot_pacf
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plot_pacf(data, lags=30)
plt.show()

"""compare AIC and RMSE:"""

from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error
from math import sqrt

# Split the data into training and testing sets
size = int(len(data) * 0.8)
train, test = data[0:size], data[size:len(data)]

models = [(0,0,0), (1,0,0), (0,0,1), (1,0,1)]

for order in models:
    model = ARIMA(train, order=order)
    fit = model.fit()

    pred = fit.forecast(len(test))

    rmse = sqrt(mean_squared_error(test, pred))

    print(f"ARIMA{order}")
    print("AIC :", fit.aic)
    print("RMSE:", rmse)
    print("-"*40)

"""| Model        | AIC         | RMSE         |
| ------------ | ----------- | ------------ |
| ARIMA(0,0,0) | **3735.55** | 5.5684       |
| ARIMA(1,0,0) | 3736.90     | **5.5661** ✅ |
| ARIMA(0,0,1) | 3736.99     | 5.5663       |
| ARIMA(1,0,1) | 3736.21     | 5.5680       |

Final Model Training
"""

from statsmodels.tsa.arima.model import ARIMA

final_model = ARIMA(train, order=(1,0,0))

final_fit = final_model.fit()

print("="*40)
print("ARIMA MODEL SUMMARY")
print("="*40)

print("Model      : ARIMA(1,0,0)")
print("City       : Chennai")
print("Variable   : Temperature_Avg")
print("ADF p-value:", result[1])
print("d Value    : 0")
print("AIC        :", round(final_fit.aic,2))

"""Forecast Test Data"""

forecast = final_fit.forecast(steps=len(test))

forecast

"""Calculate RMSE"""

from sklearn.metrics import mean_squared_error
from math import sqrt

rmse = sqrt(mean_squared_error(test, forecast))

print("RMSE =", rmse)

print("RMSE      :", round(rmse,4))

"""Actual vs Forecast Plot"""

plt.figure(figsize=(14,5))

plt.plot(test.index,
         test,
         label='Actual Temperature')

plt.plot(test.index,
         forecast,
         label='Forecast Temperature')

plt.title('ARIMA(1,0,0) Forecast vs Actual')

plt.xlabel('Date')

plt.ylabel('Temperature')

plt.legend()

plt.grid(True)

plt.show()

"""Test Multiple ARIMA Models"""

from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error
from math import sqrt
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

results = []

for p in range(0,4):
    for d in range(0,1):   # d=0 because data is stationary
        for q in range(0,4):

            try:
                model = ARIMA(train, order=(p,d,q))
                fit = model.fit()

                forecast = fit.forecast(steps=len(test))

                rmse = sqrt(mean_squared_error(test, forecast))

                results.append([
                    (p,d,q),
                    fit.aic,
                    fit.bic,
                    rmse
                ])

            except:
                continue

results_df = pd.DataFrame(
    results,
    columns=['Model','AIC','BIC','RMSE']
)

results_df = results_df.sort_values('RMSE')

results_df.head(20)

"""Show Best Model"""

best_model = results_df.iloc[0]

print("Best Model :", best_model['Model'])
print("AIC        :", best_model['AIC'])
print("BIC        :", best_model['BIC'])
print("RMSE       :", best_model['RMSE'])

"""Train Best Model Automatically"""

best_order = best_model['Model']

final_model = ARIMA(train, order=best_order)

final_fit = final_model.fit()

print(final_fit.summary())

"""Forecast Using Best Model"""

forecast = final_fit.forecast(steps=len(test))

plt.figure(figsize=(14,5))

plt.plot(test.index, test, label='Actual')

plt.plot(test.index, forecast, label='Forecast')

plt.title(f'Best ARIMA Model {best_order}')

plt.legend()

plt.grid(True)

plt.show()

"""run the larger grid search"""

from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error
from math import sqrt
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

results = []

for p in range(0,6):
    for d in range(0,1):   # d=0
        for q in range(0,6):

            try:
                model = ARIMA(train, order=(p,d,q))
                fit = model.fit()

                pred = fit.forecast(len(test))

                rmse = sqrt(mean_squared_error(test, pred))

                results.append([f"ARIMA({p},{d},{q})",
                                fit.aic,
                                fit.bic,
                                rmse])

            except:
                pass

results_df = pd.DataFrame(
    results,
    columns=['Model','AIC','BIC','RMSE']
)

results_df = results_df.sort_values('RMSE')

results_df.head(20)

"""Forecast Next 7 Days"""

future_forecast = final_fit.forecast(steps=7)

print(future_forecast)

"""Create Forecast Table"""

future_dates = pd.date_range(
    start=data.index[-1] + pd.Timedelta(days=1),
    periods=7
)

forecast_df = pd.DataFrame({
    'Date': future_dates,
    'Forecast_Temperature': future_forecast
})

forecast_df

"""Save Forecast CSV"""

forecast_df.to_csv(
    'Chennai_ARIMA_7Day_Forecast.csv',
    index=False
)

print("Forecast CSV Saved")

"""Forecast Chart"""

plt.figure(figsize=(10,5))

plt.plot(
    forecast_df['Date'],
    forecast_df['Forecast_Temperature'],
    marker='o'
)

plt.title('Next 7 Days Chennai Temperature Forecast')
plt.xlabel('Date')
plt.ylabel('Temperature')

plt.grid(True)

plt.show()

Final Summary Table

summary = pd.DataFrame({
    'Parameter':['City','Model','ADF p-value','d Value','RMSE'],
    'Value':['Chennai',
             'ARIMA(1,0,0)',
             "{:.4e}".format(result[1]),
             0,
             round(rmse,4)]
})

summary

"""Conclusion ARIMA Model
----------------------

| Item                  | Result                           |
| --------------------- | -------------------------------- |
| Dataset               | Indian Climate Dataset (Chennai) |
| Forecasting Technique | ARIMA                            |
| Best Model            | ARIMA(1,0,0)                     |
| Data Stationary       | Yes                              |
| ADF Test Result       | p-value < 0.05                   |
| Differencing Required | No                               |
| RMSE                  | 5.6095                           |
| Forecast Period       | Next 7 Days                      |
| Overall Performance   | Satisfactory                     |

"""